"https://www.{default}/":
  type: upstream
  upstream: "gatsby:http"

"https://{default}/":
    type: redirect
    to: "https://www.{default}/"

"https://www.backend.{default}/":
  type: upstream
  id: 'wordpress'
  upstream: "wordpress:http"

"https://backend.{default}/":
    type: redirect
    to: "https://www.backend.{default}/"
