"https://www.{default}/":
  type: upstream
  upstream: "gatsby:http"

"https://{default}/":
    type: redirect
    to: "https://www.{default}/"

"https://www.{default}/api":
  type: upstream
  upstream: "wordpress:http"

"https://{default}/api":
    type: redirect
    id: 'wordpress'
    to: "https://www.{default}/api"
